
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class consultas extends javax.swing.JFrame {

   Connection con = null;
   Statement stmt = null;
   String titulos[] = {"id","Nombre","Apellido","Nit"};
   String fila[] = new String [7];
   DefaultTableModel modelo;

    public consultas() {
        initComponents();
        this.setTitle("consulta personas");
        this.setLocation(335,200);
        this.setResizable(false);
        ImageIcon icono = new ImageIcon("");
        this.setIconImage(icono.getImage());

                try {
            
            String url = "jdbc:mysql://localhost:3306/finproyect";
            String persona = "root";
            String contraseña = "";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,persona,contraseña);
               if (con != null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select* from personas");
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {
                   
                   fila[0] = rs.getString("id");
                   fila[1] = rs.getString("nombre");
                   fila[2] = rs.getString("apellido");
                   fila[3] = rs.getString("nit");

                   
                   modelo.addRow(fila);     
               }
               tabla_usuarios.setModel(modelo);
               
                TableColumn ci = tabla_usuarios.getColumn("Id");
                ci.setMaxWidth(10);
                TableColumn cn = tabla_usuarios.getColumn("Nombre");
                cn.setMaxWidth(165);
                TableColumn cd = tabla_usuarios.getColumn("Apellido");
                cd.setMaxWidth(160);
                TableColumn ct = tabla_usuarios.getColumn("Nit");
                ct.setMaxWidth(90);
               
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"CONECTANDO A BASE DE DATOS");
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        atendercliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barramenu = new javax.swing.JMenuBar();
        menuarchivo = new javax.swing.JMenu();
        menuregistro = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_usuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 100));

        atendercliente.setBackground(new java.awt.Color(51, 51, 255));
        atendercliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atendercliente.setForeground(new java.awt.Color(0, 204, 204));
        atendercliente.setText("ATENDER AL CLIENTE");
        atendercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderclienteActionPerformed(evt);
            }
        });
        getContentPane().add(atendercliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/123.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        menuarchivo.setText("ARCHIVO");

        menuregistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuregistro.setText("Registro ");
        menuregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregistroActionPerformed(evt);
            }
        });
        menuarchivo.add(menuregistro);

        barramenu.add(menuarchivo);

        setJMenuBar(barramenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregistroActionPerformed
        this.dispose();
        persona p = new persona();
 p.setVisible(true);
    }//GEN-LAST:event_menuregistroActionPerformed

    private void atenderclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderclienteActionPerformed
       this.dispose();
      atender at = new atender();
      at.setVisible(true);
    }//GEN-LAST:event_atenderclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atendercliente;
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuarchivo;
    private javax.swing.JMenuItem menuregistro;
    private javax.swing.JTable tabla_usuarios;
    // End of variables declaration//GEN-END:variables
}
